### ISSUE TITLE
你好，关于训练mini llama2的小疑问

### ISSUE THREAD

**Issue by saltyduckegg** [chenyangMl/llama2.c-zh#1]
你好，我有个关于编码表的小问题。为什么你选用了将中文的编码插入原本llama2c提供的编码表中来训练双语故事模型。而不是完全重新根据翻译后的数据集构建纯中文的编码表训练纯中文的故事模型呢。

这看起来加入中文之后loss值无法降低到类似于纯英文数据集的水平。所以为什么不尝试下纯中文的语料呢，这样这两个模型才有可比性。

**Comment by saltyduckegg** [comment]
此外还有一个疑问，对于迷你llama2模型而言。我们真的需要使用32k这么大的词汇表吗？。词汇表的大小对训练效果的影响是怎么样的呢？我目前在尝试他在很小的词汇表上运行。但是结果并没有发现有很大的区别。（也许是我没有一个好的评价训练效果的方法？）

**Comment by chenyangMl** [comment]
这是个好问题,
其实TinyStories原文论文把词表砍到10K, 我觉得这个量级就很好.   本来初衷是想fellow的, 网上找到的中文数据随便一跑就超了. 就没用自定义的词表.

还有一个方法是找一份比较常用的语料数据,像论文中一样只保留常用token. 

所以您提到的32k在这个小场景是没啥必要.
