### ISSUE TITLE
通过这个模型是否可以用向量库来存自己的知识库呢

### ISSUE THREAD

**Issue by feishu** [chenyangMl/llama2.c-zh#4]
你好，是否可以通过这个llama2.c 然后用110M的模来弄问答自定义的知识库呢
现在就是想通过通过用户添加的知识库来回答回题

是否需要每次都需要训练一次，按你的红楼梦来

**Comment by chenyangMl** [comment]
> 你好，是否可以通过这个llama2.c 然后用110M的模来弄问答自定义的知识库呢 现在就是想通过通过用户添加的知识库来回答回题
> 
> 是否需要每次都需要训练一次，按你的红楼梦来

做基于用户知识库的QA，这里建议使用LLm+外挂额外知识库的方式来实现。
可参考Langchain的方案，[chatGLM+langchain](https://zhuanlan.zhihu.com/p/630200571)
