### ISSUE TITLE
关于run.c中matmul的疑问

### ISSUE THREAD

**Issue by KangkangStu** [chenyangMl/llama2.c-zh#7]
作为一个刚接触transformer的小白，对于run.c中的矩阵乘算子有一些疑问，作者能否回答一下。
![image](https://github.com/chenyangMl/llama2.c-zh/assets/124141787/5250196b-4f7f-477e-82ac-413587c11958)
在forward函数中可以看到，在计算qkv的时候调用了matmul函数，但是实际的matmul中完成的是一个一维向量乘矩阵的计算，那么得到的qkv也是一个1*dim的向量。但是在我接触的transformer中，qkv不应该是一个二维矩阵吗？这里有一点疑问，希望作者可以解答一下！！感谢

**Comment by chenyangMl** [comment]
这里应该使用的是 KV cache的一个优化加速方法，所以每次q, k,v都是1 x dim进行计算的。避免了重复对过去的token的计算。

推荐阅读: 
 https://twitter.com/cwolferesearch/status/1689388468911132672
 https://www.dipkumar.dev/becoming-the-unbeatable/posts/gpt-kvcache/

**Comment by KangkangStu** [comment]
xi

> 这里应该使用的是 KV cache的一个优化加速方法，所以每次q, k,v都是1 x dim进行计算的。避免了重复对过去的token的计算。
> 
> 推荐阅读: https://twitter.com/cwolferesearch/status/1689388468911132672 https://www.dipkumar.dev/becoming-the-unbeatable/posts/gpt-kvcache/

谢谢您的解答，对我的帮助非常大！祝您工作顺利！
