### ISSUE TITLE
关于训练tinyfictions的问题

### ISSUE THREAD

**Issue by hiinfinity** [chenyangMl/llama2.c-zh#8]
你好，在尝试用tinyfictions训练写红楼梦，将参数调小后效果似乎不是很好，请问train.py中的参数设置也是修改batch_size=256，其他均保持不变么？谢谢

‘’‘
利用重构的tokenizer进行训练, 先修改 config.py 中的词表路径为对应路径
下载和预处理token
python dataProcess/tinyfictions.py download

python dataProcess/tinyfictions.py pretokenize

训练. 修改batch_size=256, vocab_size=自定义的词表长度, 其他根据需要进行调整
python train.py

提供一个测试模型(10k词表)：wget https://huggingface.co/52AI/fictions/resolve/main/model-hlmeng.bin
‘’‘

**Comment by chenyangMl** [comment]
> 你好，在尝试用tinyfictions训练写红楼梦，将参数调小后效果似乎不是很好，请问train.py中的参数设置也是修改batch_size=256，其他均保持不变么？谢谢
> 
> ‘’‘ 利用重构的tokenizer进行训练, 先修改 config.py 中的词表路径为对应路径 下载和预处理token python dataProcess/tinyfictions.py download
> 
> python dataProcess/tinyfictions.py pretokenize
> 
> 训练. 修改batch_size=256, vocab_size=自定义的词表长度, 其他根据需要进行调整 python train.py
> 
> 提供一个测试模型(10k词表)：wget https://huggingface.co/52AI/fictions/resolve/main/model-hlmeng.bin ‘’‘

该工程无法实现使用tinyfictions写红楼梦，工程核心是SLM的base训练和端测推理的示例。工程提供的红楼梦.txt 是示例用来训练词表tokenizer的。

如果你想实现LM写红楼梦, 需要
1) 先准备大量的中文语料作为base模型的训练，
2) 再使用红楼梦的数据基于base模型进行模型微调得到微调模型。
